version: "3.7"

services:
  item-app:
    image: ghcr.io/andyemwe2/item-app:v1
    ports:
      - "80:8080"
    depends_on:
      - item-db
    restart: on-failure

  item-db:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - "app-db:/data/db"

volumes:
  app-db:

networks:
  net-item:
    driver: bridge
